### ISSUE TITLE
feat: bump esbuild version to v0.8.x

### ISSUE THREAD

**Issue by antfu** [nuxt-contrib/siroc#205]
**🆒 Your use case**

Currently, siroc uses `esbuild@0.7.x` which is incompatible with Apple M1 chips and causes installing failures. The M1 support for esbuild starts from `0.8.47`.

**🆕 The solution you'd like**

bump esbuild version to v0.8.x, and migrate the API changes.

**🔍 Alternatives you've considered**
Have you considered any alternative solutions or features?

**ℹ️ Additional info**
Is there any other context you think would be helpful to know?

Installing:

![image](https://user-images.githubusercontent.com/11247099/109287978-403e8f00-785f-11eb-920f-c5cdc7838faa.png)

Force resolutions with:

```json
  "resolutions": {
    "esbuild": "0.8.52"
  },
```

The installing works, but `siroc build` failed:

![image](https://user-images.githubusercontent.com/11247099/109288119-6b28e300-785f-11eb-95f5-2bbafdb64a7a.png)

**Comment by danielroe** [comment]
Thanks for the prompt!
